#!/usr/bin/env node
/**
 * Audit stale `@diplodoc/*` dependencies in the master branches of all repos
 * listed in release-train.yml.
 *
 * With --create-issue the report becomes a drift issue whose hidden
 * `RT-STATE.drift` holds a machine-readable update plan; commenting `/rt start`
 * on that issue turns the plan into dependency-update PRs and a release train.
 *
 * Usage:
 *   node scripts/release-train/audit-drift.js [--repos cli,transform]
 *        [--deps @diplodoc/utils] [--create-issue] [--fail-on-stale]
 */

import { appendFileSync, writeFileSync } from 'node:fs';
import { parseArgs } from 'node:util';
import { loadConfig, trainContext } from './config.js';
import {
  buildUpdatePlan,
  classifyDependency,
  renderDriftTable,
  SECTIONS,
} from './drift.js';
import { appendSummary } from './render-summary.js';
import { npmLatestVersion, readPackageJsonFromRepo } from './wait-npm.js';
import {
  DRIFT_COMMANDS_HINT,
  DRIFT_LABEL,
  ensureTrainIssue,
  normalizeTrainId,
  renderIssueBody,
  updateTrainIssue,
} from './tracking-issue.js';

const { values } = parseArgs({
  options: {
    'train-id': { type: 'string' },
    repos: { type: 'string' },
    deps: { type: 'string' },
    'create-issue': { type: 'boolean', default: false },
    'fail-on-stale': { type: 'boolean', default: false },
    output: { type: 'string', default: 'drift.json' },
  },
});

const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN;
if (!token) {
  console.error('GH_TOKEN is required');
  process.exit(1);
}

const config = loadConfig();
const { org, issueOwner, issueRepo, targetBranch } = trainContext(config);

const runNumber = process.env.GITHUB_RUN_NUMBER || process.env.GITHUB_RUN_ID || Date.now();
// Drift trains get their own id namespace so an audit can never collide with
// a `rt-<run number>` id generated by the release train workflow.
const trainId = normalizeTrainId(values['train-id']) || normalizeTrainId(`rt-drift-${runNumber}`);

const repoFilter = values.repos
  ? new Set(values.repos.split(',').map((s) => s.trim()).filter(Boolean))
  : null;
const depFilter = values.deps
  ? new Set(values.deps.split(',').map((s) => s.trim()).filter(Boolean))
  : null;

const latestCache = new Map();
function latestOf(name) {
  if (!latestCache.has(name)) latestCache.set(name, npmLatestVersion(name));
  return latestCache.get(name);
}

const rows = [];
const skipped = [];

for (const [slug, repoCfg] of Object.entries(config.repos)) {
  if (!repoCfg.npm) continue;
  if (repoFilter && !repoFilter.has(slug)) continue;

  let pkg;
  try {
    pkg = readPackageJsonFromRepo(org, slug, targetBranch, token);
  } catch (err) {
    skipped.push({ repo: slug, reason: err.message.split('\n')[0] });
    console.warn(`::warning::Could not read package.json from ${org}/${slug}: ${err.message}`);
    continue;
  }

  for (const section of SECTIONS) {
    for (const [name, declared] of Object.entries(pkg[section] || {})) {
      if (!name.startsWith('@diplodoc/')) continue;
      if (depFilter && !depFilter.has(name)) continue;

      const latest = latestOf(name);
      if (!latest) continue;

      const verdict = classifyDependency(declared, latest);
      if (!verdict.comparable || !verdict.stale) continue;

      rows.push({
        repo: slug,
        name,
        section,
        declared,
        latest,
        allowsLatest: verdict.allowsLatest,
      });
    }
  }
}

rows.sort((a, b) => a.repo.localeCompare(b.repo) || a.name.localeCompare(b.name));

const updates = buildUpdatePlan(rows);
const drift = { mode: 'dependency-drift', targetBranch, generatedAt: new Date().toISOString(), updates };

writeFileSync(values.output, JSON.stringify({ trainId, rows, drift, skipped }, null, 2) + '\n');

const table = renderDriftTable(rows);
console.log(table);
console.log(`\n${rows.length} stale dependency declaration(s) across ${updates.length} repo(s).`);

let issue = null;
if (values['create-issue']) {
  const sections = [
    { heading: 'Stale dependencies', body: table },
    updates.length
      ? {
          heading: 'Planned updates',
          body: updates
            .map(
              (u) =>
                `- \`${u.repo}\`: ${u.packages.map((p) => `\`${p.name}\`${p.section === 'devDependencies' ? ' (dev)' : ''}`).join(', ')}`,
            )
            .join('\n'),
        }
      : null,
    skipped.length
      ? {
          heading: 'Skipped repos',
          body: skipped.map((s) => `- \`${s.repo}\`: ${s.reason}`).join('\n'),
        }
      : null,
  ].filter(Boolean);

  issue = ensureTrainIssue({
    owner: issueOwner,
    repo: issueRepo,
    trainId,
    token,
    extraLabels: [DRIFT_LABEL],
  });

  const body = renderIssueBody({
    trainId,
    mode: 'dependency-drift',
    status: rows.length ? 'stale-dependencies' : 'up-to-date',
    title: `Dependency drift: ${trainId}`,
    sections,
    hint: DRIFT_COMMANDS_HINT,
    rtState: {
      version: 1,
      trainId,
      mode: 'dependency-drift',
      status: 'planned',
      issue: { owner: issueOwner, repo: issueRepo, number: issue.number, url: issue.url },
      updatedAt: new Date().toISOString(),
      publishedByNpm: {},
      participants: [],
      drift,
      state: { packages: [] },
    },
  });

  updateTrainIssue({ owner: issueOwner, repo: issueRepo, issueNumber: issue.number, body, token });
  console.log(`Drift issue: ${issue.url}`);
}

appendSummary(
  [
    `## Dependency drift — ${trainId}`,
    '',
    table,
    '',
    issue ? `**Drift issue:** [${issue.url}](${issue.url})` : '',
  ]
    .filter(Boolean)
    .join('\n'),
);

if (process.env.GITHUB_OUTPUT) {
  appendFileSync(
    process.env.GITHUB_OUTPUT,
    [
      `train_id=${trainId}`,
      `stale_count=${rows.length}`,
      `issue_number=${issue?.number ?? ''}`,
      `issue_url=${issue?.url ?? ''}`,
      '',
    ].join('\n'),
  );
}

if (values['fail-on-stale'] && rows.length) {
  console.error(`::error::${rows.length} stale @diplodoc/* dependency declaration(s) found`);
  process.exit(1);
}
