# Pulse — status of submodules (master)

Status badges for workflows created from [@diplodoc/lint](devops/lint) scaffolding (`lint init` / `lint update`).  
Branch: **master**. Release badge reflects last run (event: `release: published` or `workflow_dispatch`).

Workflows: [tests](.github/workflows/tests.yml) · [release](.github/workflows/release.yml) · [security](.github/workflows/security.yml)

**Version:** npm latest for packages/extensions/devops (link → GitHub Releases); GitHub release for actions.

---

## packages

| Submodule | version | tests | release | security | coverage |
|-----------|:-------:|:-------:|:-------:|:-------:|:-------:|
| [packages/cli](https://github.com/diplodoc-platform/cli) | [![version](https://img.shields.io/npm/v/@diplodoc/cli)](https://github.com/diplodoc-platform/cli/releases) | [![tests](https://github.com/diplodoc-platform/cli/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/cli/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/cli/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/cli/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/cli/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/cli/actions/workflows/security.yml) | [![Coverage](https://sonarcloud.io/api/project_badges/measure?project=diplodoc-platform_cli&metric=coverage)](https://sonarcloud.io/summary/new_code?id=diplodoc-platform_cli) |
| [packages/client](https://github.com/diplodoc-platform/client) | [![version](https://img.shields.io/npm/v/@diplodoc/client)](https://github.com/diplodoc-platform/client/releases) | [![tests](https://github.com/diplodoc-platform/client/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/client/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/client/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/client/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/client/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/client/actions/workflows/security.yml) | - |
| [packages/components](https://github.com/diplodoc-platform/components) | [![version](https://img.shields.io/npm/v/@diplodoc/components)](https://github.com/diplodoc-platform/components/releases) | [![tests](https://github.com/diplodoc-platform/components/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/components/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/components/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/components/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/components/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/components/actions/workflows/security.yml) | - |
| [packages/directive](https://github.com/diplodoc-platform/directive) | [![version](https://img.shields.io/npm/v/@diplodoc/directive)](https://github.com/diplodoc-platform/directive/releases) | [![tests](https://github.com/diplodoc-platform/directive/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/directive/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/directive/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/directive/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/directive/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/directive/actions/workflows/security.yml) | - |
| [packages/gh-docs](https://github.com/diplodoc-platform/gh-docs) | [![version](https://img.shields.io/npm/v/@diplodoc/gh-docs)](https://github.com/diplodoc-platform/gh-docs/releases) | [![tests](https://github.com/diplodoc-platform/gh-docs/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/gh-docs/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/gh-docs/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/gh-docs/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/gh-docs/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/gh-docs/actions/workflows/security.yml) | - |
| [packages/liquid](https://github.com/diplodoc-platform/liquid) | [![version](https://img.shields.io/npm/v/@diplodoc/liquid)](https://github.com/diplodoc-platform/liquid/releases) | [![tests](https://github.com/diplodoc-platform/liquid/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/liquid/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/liquid/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/liquid/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/liquid/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/liquid/actions/workflows/security.yml) | - |
| [packages/sentenizer](https://github.com/diplodoc-platform/sentenizer) | [![version](https://img.shields.io/npm/v/@diplodoc/sentenizer)](https://github.com/diplodoc-platform/sentenizer/releases) | [![tests](https://github.com/diplodoc-platform/sentenizer/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/sentenizer/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/sentenizer/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/sentenizer/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/sentenizer/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/sentenizer/actions/workflows/security.yml) | - |
| [packages/transform](https://github.com/diplodoc-platform/transform) | [![version](https://img.shields.io/npm/v/@diplodoc/transform)](https://github.com/diplodoc-platform/transform/releases) | [![tests](https://github.com/diplodoc-platform/transform/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/transform/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/transform/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/transform/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/transform/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/transform/actions/workflows/security.yml) | - |
| [packages/translation](https://github.com/diplodoc-platform/translation) | [![version](https://img.shields.io/npm/v/@diplodoc/translation)](https://github.com/diplodoc-platform/translation/releases) | [![tests](https://github.com/diplodoc-platform/translation/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/translation/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/translation/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/translation/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/translation/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/translation/actions/workflows/security.yml) | - |
| [packages/utils](https://github.com/diplodoc-platform/utils) | [![version](https://img.shields.io/npm/v/@diplodoc/utils)](https://github.com/diplodoc-platform/utils/releases) | [![tests](https://github.com/diplodoc-platform/utils/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/utils/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/utils/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/utils/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/utils/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/utils/actions/workflows/security.yml) | - |
| [packages/yfmlint](https://github.com/diplodoc-platform/yfmlint) | [![version](https://img.shields.io/npm/v/@diplodoc/yfmlint)](https://github.com/diplodoc-platform/yfmlint/releases) | [![tests](https://github.com/diplodoc-platform/yfmlint/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/yfmlint/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/yfmlint/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/yfmlint/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/yfmlint/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/yfmlint/actions/workflows/security.yml) | - |
---

## extensions

| Submodule | version | tests | release | security | coverage |
|-----------|:-------:|:-------:|:-------:|:-------:|:-------:|
| [extensions/algolia](https://github.com/diplodoc-platform/algolia-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/algolia-extension)](https://github.com/diplodoc-platform/algolia-extension/releases) | [![tests](https://github.com/diplodoc-platform/algolia-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/algolia-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/algolia-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/algolia-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/algolia-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/algolia-extension/actions/workflows/security.yml) | - |
| [extensions/color](https://github.com/diplodoc-platform/color-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/color-extension)](https://github.com/diplodoc-platform/color-extension/releases) | [![tests](https://github.com/diplodoc-platform/color-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/color-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/color-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/color-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/color-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/color-extension/actions/workflows/security.yml) | - |
| [extensions/cut](https://github.com/diplodoc-platform/cut-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/cut-extension)](https://github.com/diplodoc-platform/cut-extension/releases) | [![tests](https://github.com/diplodoc-platform/cut-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/cut-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/cut-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/cut-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/cut-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/cut-extension/actions/workflows/security.yml) | - |
| [extensions/file](https://github.com/diplodoc-platform/file-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/file-extension)](https://github.com/diplodoc-platform/file-extension/releases) | [![tests](https://github.com/diplodoc-platform/file-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/file-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/file-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/file-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/file-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/file-extension/actions/workflows/security.yml) | - |
| [extensions/folding-headings](https://github.com/diplodoc-platform/folding-headings-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/folding-headings-extension)](https://github.com/diplodoc-platform/folding-headings-extension/releases) | [![tests](https://github.com/diplodoc-platform/folding-headings-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/folding-headings-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/folding-headings-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/folding-headings-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/folding-headings-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/folding-headings-extension/actions/workflows/security.yml) | - |
| [extensions/html](https://github.com/diplodoc-platform/html-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/html-extension)](https://github.com/diplodoc-platform/html-extension/releases) | [![tests](https://github.com/diplodoc-platform/html-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/html-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/html-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/html-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/html-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/html-extension/actions/workflows/security.yml) | - |
| [extensions/latex](https://github.com/diplodoc-platform/latex-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/latex-extension)](https://github.com/diplodoc-platform/latex-extension/releases) | [![tests](https://github.com/diplodoc-platform/latex-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/latex-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/latex-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/latex-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/latex-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/latex-extension/actions/workflows/security.yml) | - |
| [extensions/mermaid](https://github.com/diplodoc-platform/mermaid-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/mermaid-extension)](https://github.com/diplodoc-platform/mermaid-extension/releases) | [![tests](https://github.com/diplodoc-platform/mermaid-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/mermaid-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/mermaid-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/mermaid-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/mermaid-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/mermaid-extension/actions/workflows/security.yml) | - |
| [extensions/openapi](https://github.com/diplodoc-platform/openapi-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/openapi-extension)](https://github.com/diplodoc-platform/openapi-extension/releases) | [![tests](https://github.com/diplodoc-platform/openapi-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/openapi-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/openapi-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/openapi-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/openapi-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/openapi-extension/actions/workflows/security.yml) | - |
| [extensions/page-constructor](https://github.com/diplodoc-platform/page-constructor-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/page-constructor-extension)](https://github.com/diplodoc-platform/page-constructor-extension/releases) | [![tests](https://github.com/diplodoc-platform/page-constructor-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/page-constructor-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/page-constructor-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/page-constructor-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/page-constructor-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/page-constructor-extension/actions/workflows/security.yml) | - |
| [extensions/quote-link](https://github.com/diplodoc-platform/quote-link-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/quote-link-extension)](https://github.com/diplodoc-platform/quote-link-extension/releases) | [![tests](https://github.com/diplodoc-platform/quote-link-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/quote-link-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/quote-link-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/quote-link-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/quote-link-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/quote-link-extension/actions/workflows/security.yml) | - |
| [extensions/search](https://github.com/diplodoc-platform/search-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/search-extension)](https://github.com/diplodoc-platform/search-extension/releases) | [![tests](https://github.com/diplodoc-platform/search-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/search-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/search-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/search-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/search-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/search-extension/actions/workflows/security.yml) | - |
| [extensions/tabs](https://github.com/diplodoc-platform/tabs-extension) | [![version](https://img.shields.io/npm/v/@diplodoc/tabs-extension)](https://github.com/diplodoc-platform/tabs-extension/releases) | [![tests](https://github.com/diplodoc-platform/tabs-extension/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/tabs-extension/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/tabs-extension/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/tabs-extension/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/tabs-extension/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/tabs-extension/actions/workflows/security.yml) | - |
---

## devops

| Submodule | version | tests | release | security |
|-----------|:-------:|:-------:|:-------:|:-------:|
| [devops/babel-preset](https://github.com/diplodoc-platform/babel-preset) | [![version](https://img.shields.io/npm/v/@diplodoc/babel-preset)](https://github.com/diplodoc-platform/babel-preset/releases) | - | [![release](https://github.com/diplodoc-platform/babel-preset/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/babel-preset/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/babel-preset/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/babel-preset/actions/workflows/security.yml) |
| [devops/lint](https://github.com/diplodoc-platform/lint) | [![version](https://img.shields.io/npm/v/@diplodoc/lint)](https://github.com/diplodoc-platform/lint/releases) | [![tests](https://github.com/diplodoc-platform/lint/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/lint/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/lint/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/lint/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/lint/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/lint/actions/workflows/security.yml) |
| [devops/package-template](https://github.com/diplodoc-platform/package-template) | - | - | - | [![security](https://github.com/diplodoc-platform/package-template/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/package-template/actions/workflows/security.yml) |
| [devops/testpack](https://github.com/diplodoc-platform/testpack) | [![version](https://img.shields.io/npm/v/@diplodoc/testpack)](https://github.com/diplodoc-platform/testpack/releases) | [![tests](https://github.com/diplodoc-platform/testpack/actions/workflows/tests.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/testpack/actions/workflows/tests.yml) | [![release](https://github.com/diplodoc-platform/testpack/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/testpack/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/testpack/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/testpack/actions/workflows/security.yml) |
| [devops/tsconfig](https://github.com/diplodoc-platform/tsconfig) | [![version](https://img.shields.io/npm/v/@diplodoc/tsconfig)](https://github.com/diplodoc-platform/tsconfig/releases) | - | [![release](https://github.com/diplodoc-platform/tsconfig/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/tsconfig/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/tsconfig/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/tsconfig/actions/workflows/security.yml) |
---

## actions

| Submodule | version | release | security |
|-----------|:-------:|:-------:|:-------:|
| [actions/docs-build](https://github.com/diplodoc-platform/docs-build-action) | [![version](https://img.shields.io/github/v/release/diplodoc-platform/docs-build-action)](https://github.com/diplodoc-platform/docs-build-action/releases) | [![release](https://github.com/diplodoc-platform/docs-build-action/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/docs-build-action/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/docs-build-action/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/docs-build-action/actions/workflows/security.yml) |
| [actions/docs-build-static](https://github.com/diplodoc-platform/docs-build-static-action) | [![version](https://img.shields.io/github/v/release/diplodoc-platform/docs-build-static-action)](https://github.com/diplodoc-platform/docs-build-static-action/releases) | [![release](https://github.com/diplodoc-platform/docs-build-static-action/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/docs-build-static-action/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/docs-build-static-action/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/docs-build-static-action/actions/workflows/security.yml) |
| [actions/docs-clean](https://github.com/diplodoc-platform/docs-clean-action) | [![version](https://img.shields.io/github/v/release/diplodoc-platform/docs-clean-action)](https://github.com/diplodoc-platform/docs-clean-action/releases) | [![release](https://github.com/diplodoc-platform/docs-clean-action/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/docs-clean-action/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/docs-clean-action/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/docs-clean-action/actions/workflows/security.yml) |
| [actions/docs-message](https://github.com/diplodoc-platform/docs-message-action) | [![version](https://img.shields.io/github/v/release/diplodoc-platform/docs-message-action)](https://github.com/diplodoc-platform/docs-message-action/releases) | [![release](https://github.com/diplodoc-platform/docs-message-action/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/docs-message-action/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/docs-message-action/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/docs-message-action/actions/workflows/security.yml) |
| [actions/docs-release](https://github.com/diplodoc-platform/docs-release-action) | [![version](https://img.shields.io/github/v/release/diplodoc-platform/docs-release-action)](https://github.com/diplodoc-platform/docs-release-action/releases) | [![release](https://github.com/diplodoc-platform/docs-release-action/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/docs-release-action/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/docs-release-action/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/docs-release-action/actions/workflows/security.yml) |
| [actions/docs-upload](https://github.com/diplodoc-platform/docs-upload-action) | [![version](https://img.shields.io/github/v/release/diplodoc-platform/docs-upload-action)](https://github.com/diplodoc-platform/docs-upload-action/releases) | [![release](https://github.com/diplodoc-platform/docs-upload-action/actions/workflows/release.yml/badge.svg)](https://github.com/diplodoc-platform/docs-upload-action/actions/workflows/release.yml) | [![security](https://github.com/diplodoc-platform/docs-upload-action/actions/workflows/security.yml/badge.svg?branch=master)](https://github.com/diplodoc-platform/docs-upload-action/actions/workflows/security.yml) |
